spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rental_db
    username: postgres
    password: ${DB_PASSWORD:postgres}
  
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        use_sql_comments: false

app:
  storage:
    local:
      upload-dir: /var/www/rental-images/properties
      base-url: https://ksdcnit.com
  image:
    base-url: https://ksdcnit.com

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.servlet.config.annotation.CorsRegistry: TRACE