import { StyleSheet } from 'react-native';
import { colors, spacing, shadows, borderRadius, typography } from '../styles/common';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: colors.background,
  },
  container: {
    padding: 6,
    paddingTop: spacing.xs,
    backgroundColor: colors.background,
    flexGrow: 1,
  },
  scrollContent: {
    paddingBottom: spacing.lg,
  },
  narrowContainer: {
    paddingHorizontal: 6,
  },
  headerSection: {
    marginBottom: spacing.sm,
    marginTop: spacing.xs,
  },
  title: {
    fontSize: 18,
    lineHeight: 22,
    fontWeight: '700',
    marginBottom: spacing.xs,
    color: colors.textPrimary,
  },
  description: {
    fontSize: 11,
    color: colors.textSecondary,
    marginBottom: spacing.sm,
    lineHeight: 14,
  },
  editAction: {
    alignSelf: 'flex-start',
    borderColor: colors.primary,
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    marginTop: spacing.xs,
  },
  editActionText: {
    color: colors.primaryDark,
    fontSize: 11,
    fontWeight: '700',
  },
  priceContainer: {
    backgroundColor: '#102A43',
    paddingVertical: 6,
    paddingHorizontal: spacing.sm,
    borderRadius: 8,
    marginBottom: 6,
    ...shadows.md,
  },
  priceLabel: {
    fontSize: 9,
    color: colors.surfaceLight,
    opacity: 0.9,
    marginBottom: spacing.xs,
  },
  priceValue: {
    fontSize: 19,
    fontWeight: '700',
    color: '#F4C95D',
  },
  infoCard: {
    backgroundColor: colors.surfaceLight,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E9E1D7',
    padding: 6,
    marginBottom: 6,
    ...shadows.md,
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 4,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  infoGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 4,
    paddingVertical: 4,
  },
  infoRowCompact: {
    width: '48%',
    minHeight: 48,
    borderWidth: 1,
    borderBottomWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    paddingHorizontal: 5,
    paddingVertical: 3,
  },
  infoRowLast: {
    borderBottomWidth: 0,
  },
  infoIcon: {
    fontSize: 13,
    marginRight: 4,
    width: 16,
  },
  infoContent: {
    flex: 1,
  },
  label: {
    fontWeight: '600',
    color: colors.textSecondary,
    marginBottom: spacing.xs,
    fontSize: 9,
  },
  value: {
    fontSize: 11,
    fontWeight: '600',
    color: colors.textPrimary,
    flexShrink: 1,
  },
  contactCard: {
    backgroundColor: '#D9F3E8',
    borderRadius: 10,
    padding: spacing.sm,
    marginBottom: spacing.sm,
    ...shadows.md,
  },
  contactActions: {
    backgroundColor: '#102A43',
    borderRadius: 10,
    padding: 8,
    marginBottom: 8,
  },
  contactActionsTitle: {
    color: colors.surfaceLight,
    fontSize: 11,
    fontWeight: '700',
    marginBottom: 6,
  },
  featuresCard: {
    backgroundColor: colors.surfaceLight,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 8,
    padding: 6,
    marginBottom: 6,
  },
  featuresTitle: {
    color: colors.textPrimary,
    fontSize: 12,
    fontWeight: '700',
    marginBottom: spacing.sm,
  },
  statusRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.xs,
  },
  availableBadge: {
    color: colors.secondaryDark,
    backgroundColor: '#D9F3E8',
    borderRadius: 8,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    fontSize: 12,
    fontWeight: '700',
  },
  unavailableBadge: {
    color: colors.danger,
    backgroundColor: '#FDE8E7',
    borderRadius: 8,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    fontSize: 12,
    fontWeight: '700',
  },
  visibilityBadge: {
    color: colors.textSecondary,
    backgroundColor: colors.surface,
    borderRadius: 8,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    fontSize: 12,
    fontWeight: '700',
  },
  amenitiesWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.xs,
    marginTop: spacing.md,
  },
  amenityBadge: {
    color: colors.textSecondary,
    backgroundColor: '#F7F9FB',
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    fontSize: 12,
  },
  contactLabel: {
    fontSize: 12,
    color: colors.secondaryDark,
    opacity: 0.9,
    marginBottom: spacing.sm,
  },
  contactNumber: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.secondaryDark,
  },
  ownerActions: {
    flexDirection: 'row',
    gap: spacing.sm,
    marginBottom: spacing.sm,
  },
  editButton: {
    flex: 1,
    borderColor: colors.primary,
    borderWidth: 1,
    borderRadius: 8,
    paddingVertical: spacing.sm,
    alignItems: 'center',
  },
  editButtonText: {
    color: colors.primaryDark,
    fontSize: 12,
    fontWeight: '700',
  },
  deleteButton: {
    flex: 1,
    backgroundColor: '#FDE8E7',
    borderRadius: 8,
    paddingVertical: spacing.sm,
    alignItems: 'center',
  },
  deleteButtonText: {
    color: colors.danger,
    fontSize: 12,
    fontWeight: '700',
  },
  buttonRow: {
    flexDirection: 'row',
    gap: 6,
    width: '100%',
    minHeight: 44,
    marginTop: 0,
    paddingHorizontal: 0,
  },
  buttonRowCompact: {
    flexDirection: 'column',
  },
  callBtn: {
    flex: 1,
    backgroundColor: colors.primary,
    minHeight: 42,
    paddingHorizontal: 8,
    paddingVertical: 8,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    ...shadows.md,
  },
  whatsappBtn: {
    flex: 1,
    backgroundColor: colors.whatsapp,
    minHeight: 42,
    paddingHorizontal: 8,
    paddingVertical: 8,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    ...shadows.md,
  },
  btnText: {
    color: colors.surfaceLight,
    fontSize: 11,
    fontWeight: '700',
  },
  actionBar: {
    display: 'none',
  },
});