import { StyleSheet } from 'react-native';
import { colors, spacing, shadows, borderRadius, typography } from '../styles/common';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  screenContent: {
    paddingTop: spacing.md,
    paddingBottom: spacing.xxl,
  },
  center: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.background,
  },
  header: {
    marginBottom: spacing.xl,
  },
  headerTitle: {
    fontSize: 32,
    fontWeight: '700',
    color: colors.textPrimary,
    marginBottom: spacing.sm,
  },
  headerSubtitle: {
    fontSize: 14,
    color: colors.textSecondary,
  },
  heroBanner: {
    backgroundColor: '#102A43',
    borderRadius: 24,
    padding: spacing.xl,
    marginBottom: spacing.lg,
    overflow: 'hidden',
    ...shadows.lg,
  },
  heroBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    borderRadius: borderRadius.full,
    backgroundColor: '#1E405C',
    marginBottom: spacing.md,
  },
  heroBadgeDot: {
    color: '#F4C95D',
    fontSize: 10,
    marginRight: spacing.xs,
  },
  heroBadgeText: {
    color: '#D9F3E8',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 1.2,
  },
  heroTitle: {
    color: '#FFFFFF',
    fontSize: 29,
    lineHeight: 35,
    fontWeight: '700',
    marginBottom: spacing.sm,
  },
  heroHighlight: {
    color: '#F4C95D',
  },
  heroSubtitle: {
    color: '#C9D8E5',
    fontSize: 13,
    lineHeight: 19,
    marginBottom: spacing.md,
  },
  heroFeatures: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  heroFeature: {
    width: '48%',
    minHeight: 62,
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingHorizontal: spacing.sm,
    borderRadius: borderRadius.md,
    backgroundColor: '#1B3B56',
  },
  heroFeatureIcon: {
    fontSize: 17,
    marginRight: spacing.xs,
  },
  heroFeatureText: {
    color: '#D9F3E8',
    fontSize: 10,
    fontWeight: '600',
  },
  heroFeatureCopy: {
    flex: 1,
    minWidth: 0,
  },
  heroFeatureSubtext: {
    color: 'rgba(217,243,232,0.62)',
    fontSize: 9,
    lineHeight: 12,
    marginTop: 2,
  },
  quickFiltersRow: {
    gap: spacing.sm,
    paddingBottom: spacing.md,
    paddingRight: spacing.sm,
  },
  quickFilterChip: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    width: 116,
    height: 42,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: borderRadius.full,
    backgroundColor: colors.surfaceLight,
  },
  quickFilterChipActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  quickFilterIcon: {
    marginRight: spacing.xs,
    fontSize: 14,
  },
  quickFilterText: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: '600',
    flexShrink: 0,
    includeFontPadding: false,
  },
  quickFilterTextActive: {
    color: colors.surfaceLight,
  },
  mapButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 44,
    marginBottom: spacing.md,
    borderRadius: borderRadius.md,
    backgroundColor: '#D9F3E8',
    borderWidth: 1,
    borderColor: '#A9D8C9',
    ...shadows.sm,
  },
  mapButtonIcon: {
    fontSize: 16,
    marginRight: spacing.xs,
  },
  mapButtonText: {
    color: '#236C63',
    fontWeight: '700',
  },
  ownerButton: {
    alignItems: 'center',
    marginBottom: spacing.md,
    paddingVertical: spacing.xs,
  },
  ownerButtonText: {
    color: colors.textTertiary,
    fontSize: 11,
    fontWeight: '700',
  },
  searchContainer: {
    marginBottom: spacing.lg,
  },
  searchInput: {
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.16)',
    borderRadius: 18,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    backgroundColor: '#17324D',
    fontSize: 14,
    color: '#FFFFFF',
    ...shadows.md,
  },
  searchInputPlaceholder: {
    color: colors.textTertiary,
  },
  filterActions: {
    flexDirection: 'row',
    gap: spacing.sm,
    marginTop: spacing.sm,
  },
  filterToggle: {
    flex: 1,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: borderRadius.full,
    paddingVertical: spacing.sm,
    alignItems: 'center',
  },
  filterToggleText: {
    color: colors.textSecondary,
    fontWeight: '600',
  },
  applyButton: {
    flex: 1,
    backgroundColor: colors.primary,
    borderRadius: borderRadius.full,
    paddingVertical: spacing.sm,
    alignItems: 'center',
  },
  applyButtonText: {
    color: colors.surfaceLight,
    fontWeight: '700',
  },
  filtersPanel: {
    marginTop: spacing.sm,
    padding: spacing.md,
    backgroundColor: colors.surfaceLight,
    borderRadius: borderRadius.md,
    ...shadows.sm,
  },
  filterInput: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: borderRadius.md,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    marginBottom: spacing.sm,
    color: colors.textPrimary,
  },
  filterLabel: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: '700',
    marginTop: spacing.sm,
    marginBottom: spacing.xs,
  },
  optionRow: {
    gap: spacing.xs,
    paddingVertical: spacing.xs,
  },
  optionChip: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: borderRadius.full,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    backgroundColor: colors.background,
  },
  optionChipActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  optionChipText: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: '600',
  },
  optionChipTextActive: {
    color: colors.surfaceLight,
  },
  amenitiesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.xs,
  },
  amenityChip: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: borderRadius.full,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    backgroundColor: colors.background,
  },
  clearFiltersText: {
    color: colors.primaryDark,
    fontWeight: '600',
    marginTop: spacing.xs,
  },
  listContainer: {
    paddingBottom: spacing.lg,
  },
  resultsSection: {
    width: '100%',
  },
  resultsHeader: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    marginBottom: spacing.md,
    paddingHorizontal: spacing.xs,
  },
  resultsHeadingBlock: {
    flex: 1,
    minWidth: 0,
  },
  resultsTitle: {
    color: colors.textPrimary,
    fontSize: 20,
    fontWeight: '700',
  },
  resultsSubtitle: {
    color: colors.textTertiary,
    fontSize: 12,
    marginTop: 2,
  },
  resultsSort: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: '600',
    marginLeft: spacing.sm,
    flexShrink: 1,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: spacing.lg,
  },
  emptyText: {
    fontSize: 16,
    color: colors.textSecondary,
    textAlign: 'center',
  },
  card: {
    backgroundColor: colors.surfaceLight,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#E9E1D7',
    overflow: 'hidden',
    marginBottom: spacing.lg,
    ...shadows.md,
  },
  cardImageContainer: {
    width: '100%',
    height: 196,
    backgroundColor: colors.surface,
  },
  cardContent: {
    padding: spacing.lg,
    gap: spacing.xs,
  },
  cardHeader: {
    marginBottom: spacing.md,
  },
  cardTitleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: spacing.sm,
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.textPrimary,
    flex: 1,
    marginRight: spacing.sm,
  },
  priceBadge: {
    backgroundColor: 'transparent',
    paddingHorizontal: 0,
    paddingVertical: 0,
    borderRadius: 0,
  },
  priceText: {
    color: colors.primaryDark,
    fontWeight: '700',
    fontSize: 16,
  },
  cardMeta: {
    flexDirection: 'row',
    marginBottom: spacing.md,
  },
  metaItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: spacing.lg,
  },
  metaIcon: {
    marginRight: spacing.xs,
    fontSize: 14,
  },
  metaText: {
    fontSize: 13,
    color: colors.textSecondary,
  },
  cardLocation: {
    fontSize: 13,
    color: colors.textTertiary,
    marginBottom: spacing.md,
  },
  cardBedrooms: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.secondary,
    marginBottom: spacing.md,
  },
  cardDescription: {
    fontSize: 12,
    color: colors.textSecondary,
    lineHeight: 18,
    marginBottom: spacing.md,
    fontStyle: 'italic',
  },
  buttonRow: {
    flexDirection: 'row',
    gap: spacing.sm,
    marginTop: spacing.md,
    paddingTop: spacing.md,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  callBtn: {
    flex: 1,
    backgroundColor: colors.primary,
    paddingVertical: spacing.md,
    borderRadius: borderRadius.full,
    alignItems: 'center',
    justifyContent: 'center',
    ...shadows.sm,
  },
  whatsappBtn: {
    flex: 1,
    backgroundColor: colors.whatsapp,
    paddingVertical: spacing.md,
    borderRadius: borderRadius.full,
    alignItems: 'center',
    justifyContent: 'center',
    ...shadows.sm,
  },
  btnText: {
    color: colors.surfaceLight,
    textAlign: 'center',
    fontWeight: '700',
    fontSize: 13,
  },
});