import { StyleSheet } from 'react-native';
import { colors, spacing, shadows, borderRadius, typography } from '../styles/common';

export const styles = StyleSheet.create({
  appShell: {
    flex: 1,
    backgroundColor: colors.background,
  },
  appBar: {
    minHeight: 58,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.md,
    backgroundColor: colors.surfaceLight,
    borderBottomColor: colors.border,
    borderBottomWidth: 1,
    zIndex: 10,
  },
  brand: {
    flexDirection: 'row',
    alignItems: 'center',
    minWidth: 0,
  },
  brandLogo: {
    width: 34,
    height: 34,
    borderRadius: 8,
    marginRight: spacing.sm,
  },
  brandName: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: '900',
    letterSpacing: 1.4,
  },
  brandSubname: {
    color: colors.primaryDark,
    fontSize: 8,
    fontWeight: '800',
    letterSpacing: 1.8,
    marginTop: 1,
  },
  appBarActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  authLink: {
    paddingHorizontal: 7,
    paddingVertical: 8,
  },
  authLinkText: {
    color: colors.textPrimary,
    fontSize: 12,
    fontWeight: '700',
  },
  registerLink: {
    backgroundColor: colors.primary,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  registerLinkText: {
    color: colors.surfaceLight,
    fontSize: 12,
    fontWeight: '800',
  },
  iconButton: {
    width: 34,
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 9,
  },
  iconButtonText: {
    color: colors.textPrimary,
    fontSize: 21,
    lineHeight: 23,
  },
  profileButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.secondary,
  },
  profileText: {
    color: colors.surfaceLight,
    fontSize: 13,
    fontWeight: '800',
  },
  menuPanel: {
    position: 'absolute',
    top: 58,
    right: spacing.md,
    width: 210,
    backgroundColor: colors.surfaceLight,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 10,
    padding: 5,
    zIndex: 20,
    ...shadows.md,
  },
  menuItem: {
    minHeight: 42,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.sm,
    borderRadius: 7,
  },
  menuIcon: {
    width: 25,
    color: colors.primaryDark,
    fontSize: 17,
  },
  menuText: {
    color: colors.textPrimary,
    fontSize: 13,
    fontWeight: '700',
  },
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  screenContent: {
    paddingTop: spacing.sm,
    paddingBottom: spacing.xxl,
  },
  mobileNav: {
    flexDirection: 'row',
    alignItems: 'stretch',
    justifyContent: 'space-between',
    backgroundColor: colors.surfaceLight,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 12,
    padding: 4,
    marginBottom: spacing.md,
    ...shadows.sm,
  },
  mobileNavItem: {
    flex: 1,
    minHeight: 48,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 9,
    paddingHorizontal: 2,
  },
  mobileNavItemActive: {
    backgroundColor: colors.primary,
  },
  mobileNavIcon: {
    color: colors.textSecondary,
    fontSize: 17,
    lineHeight: 19,
  },
  mobileNavText: {
    color: colors.textSecondary,
    fontSize: 10,
    fontWeight: '700',
    marginTop: 2,
  },
  mobileNavTextActive: {
    color: colors.surfaceLight,
  },
  center: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.background,
  },
  header: {
    marginBottom: spacing.xl,
  },
  headerTitle: {
    fontSize: 32,
    fontWeight: '700',
    color: colors.textPrimary,
    marginBottom: spacing.sm,
  },
  headerSubtitle: {
    fontSize: 14,
    color: colors.textSecondary,
  },
  heroBanner: {
    backgroundColor: '#102A43',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
    padding: spacing.lg,
    marginBottom: spacing.lg,
    overflow: 'hidden',
    ...shadows.md,
  },
  heroBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    borderRadius: borderRadius.full,
    backgroundColor: '#1E405C',
    marginBottom: spacing.sm,
  },
  heroBadgeDot: {
    color: '#F4C95D',
    fontSize: 10,
    marginRight: spacing.xs,
  },
  heroBadgeText: {
    color: '#D9F3E8',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 1.2,
  },
  heroTitle: {
    color: '#FFFFFF',
    fontSize: 25,
    lineHeight: 31,
    fontWeight: '700',
    marginBottom: spacing.sm,
  },
  heroHighlight: {
    color: '#F4C95D',
  },
  heroSubtitle: {
    color: '#C9D8E5',
    fontSize: 12,
    lineHeight: 17,
    marginBottom: spacing.sm,
  },
  heroFeatures: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  heroFeature: {
    width: '48%',
    minHeight: 56,
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingHorizontal: spacing.sm,
    borderRadius: borderRadius.md,
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
  },
  heroFeatureIcon: {
    fontSize: 17,
    marginRight: spacing.xs,
  },
  heroFeatureText: {
    color: '#D9F3E8',
    fontSize: 10,
    fontWeight: '600',
  },
  heroFeatureCopy: {
    flex: 1,
    minWidth: 0,
  },
  heroFeatureSubtext: {
    color: 'rgba(217,243,232,0.62)',
    fontSize: 9,
    lineHeight: 12,
    marginTop: 2,
  },
  quickFiltersRow: {
    gap: spacing.sm,
    paddingBottom: spacing.sm,
    paddingRight: spacing.sm,
  },
  quickFilterChip: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    width: 112,
    height: 38,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: borderRadius.full,
    backgroundColor: colors.surfaceLight,
  },
  quickFilterChipActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  quickFilterIcon: {
    marginRight: spacing.xs,
    fontSize: 14,
  },
  quickFilterText: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: '600',
    flexShrink: 0,
    includeFontPadding: false,
  },
  quickFilterTextActive: {
    color: colors.surfaceLight,
  },
  mapButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 42,
    marginBottom: spacing.sm,
    borderRadius: 12,
    backgroundColor: '#D9F3E8',
    borderWidth: 1,
    borderColor: '#A9D8C9',
    ...shadows.sm,
  },
  mapButtonIcon: {
    fontSize: 16,
    marginRight: spacing.xs,
  },
  mapButtonText: {
    color: '#236C63',
    fontWeight: '700',
  },
  ownerButton: {
    alignItems: 'center',
    marginBottom: spacing.sm,
    paddingVertical: spacing.xs,
  },
  ownerButtonText: {
    color: colors.textTertiary,
    fontSize: 11,
    fontWeight: '700',
  },
  searchContainer: {
    marginBottom: spacing.lg,
    paddingHorizontal: 4,
  },
  searchInputWrapper: {
    minHeight: 56,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    paddingHorizontal: 14,
    borderRadius: 18,
    backgroundColor: '#0F172A',
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.18,
    shadowRadius: 20,
    elevation: 5,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.16)',
  },
  searchInput: {
    flex: 1,
    minWidth: 0,
    paddingVertical: spacing.md,
    backgroundColor: 'transparent',
    fontSize: 14,
    color: colors.surfaceLight,
  },
  searchInputActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
  },
  searchIconButton: {
    width: 28,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  suggestionsPanel: {
    marginTop: spacing.sm,
    backgroundColor: colors.surfaceLight,
    borderRadius: 10,
    overflow: 'hidden',
    ...shadows.sm,
  },
  suggestionsHeader: {
    color: colors.textTertiary,
    fontSize: 10,
    fontWeight: '700',
    paddingHorizontal: spacing.md,
    paddingTop: spacing.sm,
    paddingBottom: spacing.xs,
  },
  suggestionItem: {
    minHeight: 42,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  suggestionText: {
    flex: 1,
    color: colors.textPrimary,
    fontSize: 12,
    fontWeight: '600',
  },
  searchInputPlaceholder: {
    color: colors.textTertiary,
  },
  filterActions: {
    flexDirection: 'row',
    gap: spacing.sm,
    marginTop: spacing.md,
    alignItems: 'center',
  },
  filterToggle: {
    flex: 1,
    minHeight: 44,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceLight,
    borderRadius: 10,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    gap: spacing.xs,
  },
  filterToggleText: {
    color: '#475569',
    fontSize: 13,
    fontWeight: '500',
  },
  applyButton: {
    flex: 1,
    minHeight: 44,
    backgroundColor: '#F97316',
    borderRadius: 10,
    paddingVertical: spacing.sm,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    gap: spacing.xs,
  },
  applyButtonText: {
    color: colors.surfaceLight,
    fontSize: 13,
    fontWeight: '700',
  },
  filtersPanel: {
    marginTop: spacing.sm,
    padding: spacing.md,
    backgroundColor: '#F7F9FB',
    borderRadius: 12,
    ...shadows.sm,
  },
  filterInput: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: borderRadius.md,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    marginBottom: spacing.sm,
    color: colors.textPrimary,
  },
  filterLabel: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: '700',
    marginTop: spacing.sm,
    marginBottom: spacing.xs,
  },
  optionRow: {
    gap: spacing.xs,
    paddingVertical: spacing.xs,
  },
  optionChip: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: borderRadius.full,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    backgroundColor: colors.background,
  },
  optionChipActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  optionChipText: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: '600',
  },
  optionChipTextActive: {
    color: colors.surfaceLight,
  },
  amenitiesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.xs,
  },
  amenityChip: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: borderRadius.full,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    backgroundColor: colors.background,
  },
  clearFiltersText: {
    color: colors.primaryDark,
    fontWeight: '600',
    marginTop: spacing.xs,
  },
  listContainer: {
    paddingBottom: spacing.lg,
  },
  resultsSection: {
    width: '100%',
  },
  resultsHeader: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    marginBottom: spacing.sm,
    paddingHorizontal: spacing.xs,
  },
  resultsHeadingBlock: {
    flex: 1,
    minWidth: 0,
  },
  resultsTitle: {
    color: colors.textPrimary,
    fontSize: 22,
    fontWeight: '700',
  },
  resultsSubtitle: {
    color: colors.textTertiary,
    fontSize: 12,
    marginTop: 2,
  },
  resultsSort: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: '600',
    marginLeft: spacing.sm,
    flexShrink: 1,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: spacing.lg,
  },
  emptyText: {
    fontSize: 16,
    color: colors.textSecondary,
    textAlign: 'center',
  },
  card: {
    flexDirection: 'row',
    backgroundColor: colors.surfaceLight,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#E9E1D7',
    overflow: 'hidden',
    marginBottom: spacing.md,
    ...shadows.md,
  },
  cardImageContainer: {
    width: '100%',
    height: 196,
    backgroundColor: colors.surface,
  },
  cardContent: {
    flex: 1,
    minWidth: 0,
    padding: spacing.md,
    gap: spacing.xs,
  },
  favoriteButton: {
    position: 'absolute',
    right: 8,
    bottom: 8,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: colors.surfaceLight,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 3,
  },
  cardHeader: {
    marginBottom: spacing.sm,
  },
  cardTitleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: spacing.xs,
  },
  cardTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: colors.textPrimary,
    flex: 1,
    marginRight: spacing.sm,
  },
  priceBadge: {
    backgroundColor: 'transparent',
    paddingHorizontal: 0,
    paddingVertical: 0,
    borderRadius: 0,
  },
  priceText: {
    color: colors.primaryDark,
    fontWeight: '700',
    fontSize: 17,
  },
  pricePeriod: {
    color: colors.textTertiary,
    fontSize: 10,
    marginTop: 1,
  },
  cardMeta: {
    flexDirection: 'row',
    marginBottom: spacing.xs,
  },
  metaItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: spacing.lg,
  },
  metaIcon: {
    marginRight: spacing.xs,
    fontSize: 14,
  },
  metaText: {
    fontSize: 13,
    color: colors.textSecondary,
  },
  cardLocation: {
    fontSize: 13,
    color: colors.textTertiary,
    marginBottom: spacing.md,
  },
  cardBedrooms: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.secondary,
    marginBottom: 0,
  },
  compactDetails: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    minWidth: 0,
  },
  compactDetail: {
    color: colors.textTertiary,
    fontSize: 11,
    flexShrink: 1,
  },
  cardDescription: {
    fontSize: 12,
    color: colors.textSecondary,
    lineHeight: 18,
    marginBottom: spacing.sm,
  },
  buttonRow: {
    flexDirection: 'row',
    gap: spacing.sm,
    marginTop: spacing.sm,
    paddingTop: spacing.sm,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  callBtn: {
    flex: 1,
    backgroundColor: colors.primary,
    paddingVertical: spacing.sm,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    ...shadows.sm,
  },
  whatsappBtn: {
    flex: 1,
    backgroundColor: colors.whatsapp,
    paddingVertical: spacing.sm,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    ...shadows.sm,
  },
  btnText: {
    color: colors.surfaceLight,
    textAlign: 'center',
    fontWeight: '700',
    fontSize: 13,
  },
});