import React, { useEffect, useState } from 'react';
import { ActivityIndicator, Alert, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { api } from '../api/client';
import { colors } from '../styles/common';

type Inquiry = { id: number; propertyTitle?: string; senderName?: string; message?: string; reply?: string; status?: string; isReceived?: boolean; isSent?: boolean };
export default function OwnerInquiriesScreen() {
  const [items, setItems] = useState<Inquiry[]>([]); const [loading, setLoading] = useState(true);
  const [replyingTo, setReplyingTo] = useState<number | null>(null); const [replyText, setReplyText] = useState('');
  useEffect(() => { api.get<Inquiry[]>('/inquiries/my-all').then(({ data }) => setItems(data || [])).catch(() => Alert.alert('Inquiries unavailable', 'Could not load inquiries.')).finally(() => setLoading(false)); }, []);
  const markRead = async (id: number) => { try { await api.patch(`/inquiries/${id}/read`); setItems((current) => current.map((item) => item.id === id ? { ...item, status: 'READ' } : item)); } catch { Alert.alert('Update failed', 'Could not mark inquiry as read.'); } };
  const sendReply = async (id: number) => { if (!replyText.trim()) return; try { await api.post(`/inquiries/${id}/reply`, { reply: replyText.trim() }); setItems((current) => current.map((item) => item.id === id ? { ...item, reply: replyText.trim(), status: 'REPLIED' } : item)); setReplyText(''); setReplyingTo(null); } catch (error: any) { Alert.alert('Reply failed', error.response?.data?.message || 'Could not send reply.'); } };
  if (loading) return <View style={styles.center}><ActivityIndicator color={colors.primary} /></View>;
  return <ScrollView contentContainerStyle={styles.container}><Text style={styles.eyebrow}>OWNER WORKSPACE</Text><Text style={styles.title}>My inquiries</Text>{items.length === 0 ? <Text style={styles.empty}>No inquiries yet.</Text> : items.map((item) => <View style={styles.card} key={item.id}><View style={styles.row}><Text style={styles.cardTitle}>{item.propertyTitle || 'Property inquiry'}</Text><Text style={styles.badge}>{item.status || 'NEW'}</Text></View><Text style={styles.meta}>{item.isReceived ? 'Received' : item.isSent ? 'Sent' : item.senderName || 'Inquiry'}</Text><Text style={styles.message}>{item.message || 'No message'}</Text>{item.reply ? <Text style={styles.reply}>Reply: {item.reply}</Text> : null}<View style={styles.actions}><TouchableOpacity onPress={() => markRead(item.id)}><Text style={styles.actionText}>Mark read</Text></TouchableOpacity>{item.isReceived ? <TouchableOpacity onPress={() => setReplyingTo(item.id)}><Text style={styles.actionText}>Reply</Text></TouchableOpacity> : null}</View>{replyingTo === item.id ? <View><TextInput style={styles.replyInput} placeholder="Write a reply" value={replyText} onChangeText={setReplyText} multiline /><TouchableOpacity style={styles.replyButton} onPress={() => sendReply(item.id)}><Text style={styles.replyButtonText}>Send reply</Text></TouchableOpacity></View> : null}</View>)}</ScrollView>;
}
const styles = StyleSheet.create({ container: { flexGrow: 1, padding: 16, backgroundColor: colors.background }, center: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.background }, eyebrow: { color: colors.primaryDark, fontSize: 10, fontWeight: '800', letterSpacing: 1.1 }, title: { color: colors.textPrimary, fontSize: 24, fontWeight: '800', marginTop: 4, marginBottom: 16 }, empty: { color: colors.textSecondary, textAlign: 'center', marginTop: 32 }, card: { backgroundColor: colors.surfaceLight, borderColor: colors.border, borderWidth: 1, borderRadius: 10, padding: 13, marginBottom: 10 }, row: { flexDirection: 'row', justifyContent: 'space-between', gap: 8 }, cardTitle: { flex: 1, color: colors.textPrimary, fontSize: 15, fontWeight: '800' }, badge: { color: colors.primaryDark, fontSize: 10, fontWeight: '800' }, meta: { color: colors.textTertiary, fontSize: 11, marginTop: 5 }, message: { color: colors.textSecondary, fontSize: 13, marginTop: 9, lineHeight: 18 }, reply: { color: colors.secondaryDark, fontSize: 12, marginTop: 9 }, actions: { flexDirection: 'row', gap: 16, marginTop: 12 }, actionText: { color: colors.primaryDark, fontSize: 12, fontWeight: '800' }, replyInput: { minHeight: 60, borderColor: colors.border, borderWidth: 1, borderRadius: 8, padding: 9, marginTop: 10, color: colors.textPrimary }, replyButton: { backgroundColor: colors.primary, borderRadius: 8, padding: 10, alignItems: 'center', marginTop: 7 }, replyButtonText: { color: colors.surfaceLight, fontWeight: '800', fontSize: 12 } });
