import React, { useEffect, useState } from 'react';
import { ActivityIndicator, Alert, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { api } from '../api/client';
import { getOwnerSession, saveOwnerSession } from '../api/session';
import { colors } from '../styles/common';

export default function OwnerProfileScreen() {
  const [form, setForm] = useState({ email: '', name: '', phone: '' });
  const [password, setPassword] = useState({ oldPassword: '', newPassword: '' });
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  useEffect(() => { api.get('/owners/profile').then(({ data }) => setForm({ email: data.email || '', name: data.name || '', phone: data.phone || '' })).catch(() => Alert.alert('Profile unavailable', 'Please sign in again.')).finally(() => setLoading(false)); }, []);
  const save = async () => { setSaving(true); try { await api.put('/owners/profile', form); const session = await getOwnerSession(); if (session) await saveOwnerSession({ ...session, ...form }); Alert.alert('Saved', 'Profile updated successfully.'); } catch (error: any) { Alert.alert('Save failed', error.response?.data?.message || 'Could not update profile.'); } finally { setSaving(false); } };
  const changePassword = async () => { if (!password.oldPassword || !password.newPassword) { Alert.alert('Missing details', 'Enter both passwords.'); return; } try { await api.put('/owners/password', password); setPassword({ oldPassword: '', newPassword: '' }); Alert.alert('Saved', 'Password changed successfully.'); } catch (error: any) { Alert.alert('Password change failed', error.response?.data?.message || 'Could not change password.'); } };
  if (loading) return <View style={styles.center}><ActivityIndicator color={colors.primary} /></View>;
  return <ScrollView contentContainerStyle={styles.container}><Text style={styles.eyebrow}>ACCOUNT</Text><Text style={styles.title}>Profile</Text>{(['name', 'email', 'phone'] as const).map((field) => <View style={styles.field} key={field}><Text style={styles.label}>{field}</Text><TextInput style={styles.input} value={form[field]} onChangeText={(value) => setForm((current) => ({ ...current, [field]: value }))} keyboardType={field === 'email' ? 'email-address' : field === 'phone' ? 'phone-pad' : 'default'} /></View>)}<TouchableOpacity style={styles.button} onPress={save} disabled={saving}><Text style={styles.buttonText}>{saving ? 'Saving...' : 'Save profile'}</Text></TouchableOpacity><Text style={styles.sectionTitle}>Change password</Text>{(['oldPassword', 'newPassword'] as const).map((field) => <TextInput key={field} style={styles.input} placeholder={field === 'oldPassword' ? 'Current password' : 'New password'} secureTextEntry value={password[field]} onChangeText={(value) => setPassword((current) => ({ ...current, [field]: value }))} />)}<TouchableOpacity style={styles.secondaryButton} onPress={changePassword}><Text style={styles.secondaryButtonText}>Change password</Text></TouchableOpacity></ScrollView>;
}
const styles = StyleSheet.create({ container: { flexGrow: 1, padding: 16, backgroundColor: colors.background }, center: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.background }, eyebrow: { color: colors.primaryDark, fontSize: 10, fontWeight: '800', letterSpacing: 1.1 }, title: { color: colors.textPrimary, fontSize: 24, fontWeight: '800', marginTop: 4, marginBottom: 18 }, field: { marginBottom: 12 }, label: { color: colors.textSecondary, fontSize: 11, fontWeight: '700', marginBottom: 4 }, input: { backgroundColor: colors.surfaceLight, borderColor: colors.border, borderWidth: 1, borderRadius: 9, padding: 11, color: colors.textPrimary, marginBottom: 8 }, button: { backgroundColor: colors.primary, borderRadius: 9, padding: 13, alignItems: 'center', marginTop: 6 }, buttonText: { color: colors.surfaceLight, fontWeight: '800' }, sectionTitle: { color: colors.textPrimary, fontSize: 16, fontWeight: '800', marginTop: 24, marginBottom: 8 }, secondaryButton: { borderColor: colors.primary, borderWidth: 1, borderRadius: 9, padding: 12, alignItems: 'center', marginTop: 4 }, secondaryButtonText: { color: colors.primaryDark, fontWeight: '800' } });
